lr: 0.02
seed: 3
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 512
val_batch: 256
test_batch: 256
num_workers: 8
model_name: 'latent-prediction'
data_filepath: './data/'
dataset: 'single_pendulum'
lr_schedule: [20, 50, 100, 300]
num_gpus: 1
epochs: 1000